# Generated by Django 4.2.6 on 2023-11-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_employees_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='contact',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
